<?xml version="1.0" encoding="utf-8"?><Database Name="MSW" Class="MSWDatabase" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=VIRTUAL-PC\SQLEXPRESS;Initial Catalog=MSW;Integrated Security=True;Pooling=False" SettingsObjectName="TeachingMonthChecker.Properties.Settings" SettingsPropertyName="MSWConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tTeachingMonth" Member="tTeachingMonths">
    <Type Name="tTeachingMonth">
      <Column Name="TeachingMonthID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="teachingMonth" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>